In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Machine Learning Tutorial/Machine Learning/Practice Task/Begaluru house price predication/Bengaluru_House_Data.csv")

In [4]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [6]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [7]:
df.shape

(13320, 9)

In [8]:
cat_col = ["area_type","availability","location","size","society","total_sqft"]

In [9]:
for col in cat_col:
  print("col : ",col)
  print(df[col].value_counts())
  print('-'*60)

col :  area_type
area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
------------------------------------------------------------
col :  availability
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
------------------------------------------------------------
col :  location
location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64
------------------------------------------------------------
col :  size
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
------------------------------------------------------------
col :  society
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
SLtalry     1
Rencyes     1
DiaveEn     1
Suiumy      1
Amionce     1
Name: count, Length: 2688, dtype: int64
------------------------------------------------------------
col :  total_sqft
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64
------------------------------------------------------------

In [10]:
drop_list = ["area_type","availability","society","balcony"]

df = df.drop(drop_list,axis=1)

In [11]:
df.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [12]:
df.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [13]:
df.isna().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [14]:
from numpy import median
# handle missing data

df["location"] = df["location"].fillna("Sarjapur Road")  # majority value
df["bath"] = df["bath"].fillna(df['bath'].median())

In [15]:
df["size"] = df["size"].fillna("2 BHK") # majority value
df["bhk"] = df["size"].str.split().str.get(0).astype(int)
df = df.drop("size",axis=1)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   total_sqft  13320 non-null  object
 2   bath        13320 non-null  float64
 3   price       13320 non-null  float64
 4   bhk         13320 non-null  int64
dtypes: float64(2), int64(1), object(2)
memory usage: 520.4+ KB

In [17]:
df[df.bhk > 20]

                       location total_sqft  bath  price  bhk
1718  2Electronic City Phase II       8000  27.0  230.0   27
4684                Munnekollal       2400  40.0  660.0   43

In [18]:
print(df['total_sqft'].value_counts())

total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64

In [19]:
# in total_sqft : convert into int (for range value take mean())

def convertRange(x):
  temp = x.split('-')
  if len(temp) == 2:
    return (float(temp[0]) + float(temp[1]))/2
  try:
    return float(x)
  except:
    return None

In [20]:
df['total_sqft'] = df['total_sqft'].apply(convertRange)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   total_sqft  13274 non-null  float64
 2   bath        13320 non-null  float64
 3   price       13320 non-null  float64
 4   bhk         13320 non-null  int64
dtypes: float64(3), int64(1), object(1)
memory usage: 520.4+ KB

In [22]:
# add col
df['price_per_sqft'] = (df['price'] * 100000 ) / df['total_sqft']

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   location        13320 non-null  object
 1   total_sqft      13274 non-null  float64
 2   bath            13320 non-null  float64
 3   price           13320 non-null  float64
 4   bhk             13320 non-null  int64
 5   price_per_sqft  13274 non-null  float64
dtypes: float64(4), int64(1), object(1)
memory usage: 624.5+ KB

In [24]:
# location col
df['location'] = df['location'].apply(lambda x : x.strip())
location_count = df['location'].value_counts()
print(sum(df['location'].value_counts() <= 10))

1054

In [25]:
location_count_less_50 = location_count[location_count <= 10]
len(location_count_less_50)

1054

In [81]:
df["location"] = df["location"].apply(lambda x: 'other' if x in location_count_less_50 else x)
print(df["location"].value_counts())

location
other                    0.156908
Whitefield               0.033555
Sarjapur  Road           0.026491
Electronic City          0.022008
Raja Rajeshwari Nagar    0.019019
                           ...
Banjara Layout           0.000543
Vishwapriya Layout       0.000543
Thyagaraja Nagar         0.000543
Vishveshwarya Layout     0.000543
Marsur                   0.000408
Name: proportion, Length: 242, dtype: float64

In [84]:
xx = df["location"].value_counts()

print(type(xx))

print(xx.head(20))

<class 'pandas.core.series.Series'>
location
other                       1155
Whitefield                   247
Sarjapur  Road               195
Electronic City              162
Raja Rajeshwari Nagar        140
Uttarahalli                  120
Haralur Road                 117
Marathahalli                 116
Bannerghatta Road            109
Hennur Road                  109
Thanisandra                  108
Hebbal                        99
Kanakpura Road                94
Electronic City Phase II      93
Yelahanka                     87
7th Phase JP Nagar            86
Bellandur                     73
KR Puram                      65
Chandapura                    62
Harlur                        60
Name: count, dtype: int64

## outlier detection and remove

In [27]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [28]:
#  total_sqft

(df['total_sqft']/df['bhk']).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [29]:
#  it means less then 300 sqft house are not possible

df = df[((df['total_sqft']/df['bhk']) >= 300)]
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838     6303.979357
std     1261.271296      1.077938    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [30]:
df.shape

(12530, 6)

In [31]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838     6303.979357
std     1261.271296      1.077938    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [32]:
demo = df

In [33]:
df = demo

In [34]:
def remove_outlier_sqft(df):
  df_output = pd.DataFrame()
  for key,subdf in df.groupby('location'):
    m = np.mean(subdf['price_per_sqft'])
    st = np.std(subdf['price_per_sqft'])

    gen_df = subdf[(subdf['price_per_sqft'] > (m-st)) & (subdf['price_per_sqft'] <= (m+st))]
    df_output = pd.concat([df_output,gen_df],ignore_index=True)
  return df_output

df = remove_outlier_sqft(df)
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10301.000000  10301.000000  10301.000000  10301.000000    10301.000000
mean    1508.440608      2.471702     91.286372      2.574896     5659.062876
std      880.694214      0.979449     86.342786      0.897649     2265.774749
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1110.000000      2.000000     49.000000      2.000000     4244.897959
50%     1286.000000      2.000000     67.000000      2.000000     5175.600739
75%     1650.000000      3.000000    100.000000      3.000000     6428.571429
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [35]:
def bhk_outlier_remover(df):
    exclude_indices = np.array([])

    for location, location_df in df.groupby('location'):
        bhk_stats = {}

        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk - 1)

            if stats and stats['count'] > 5:
                exclude_indices = np.append(
                    exclude_indices,
                    bhk_df[
                        bhk_df.price_per_sqft < (stats['mean'])
                    ].index.values
                )

    return df.drop(exclude_indices, axis='index')

In [36]:
df = bhk_outlier_remover(df)

In [37]:
df.shape

(7361, 6)

In [38]:
df = df.drop("price_per_sqft",axis=1) # this feature only use for remove oulier

In [39]:
df.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7361 entries, 0 to 10300
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    7361 non-null   object
 1   total_sqft  7361 non-null   float64
 2   bath        7361 non-null   float64
 3   price       7361 non-null   float64
 4   bhk         7361 non-null   int64
dtypes: float64(3), int64(1), object(1)
memory usage: 345.0+ KB

In [40]:
df_cleaned = df

In [41]:
from sklearn.linear_model import LinearRegression ,Lasso , Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [42]:
X = df_cleaned.drop(columns=['price'])
y = df_cleaned['price']

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

print(X_train.shape)
print(X_test.shape)

(5888, 4)
(1473, 4)

In [44]:
cat_cols = ['location']
num_cols = ['total_sqft', 'bath', 'bhk']

# Applying Linear Regression

In [45]:
# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(
            handle_unknown='ignore'
        ), cat_cols),

        ('num', StandardScaler(), num_cols)
    ]
)

In [46]:
# Complete pipeline
pipe_lr = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])

In [48]:
pipe_lr.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location']),
                                                 ('num', StandardScaler(),
                                                  ['total_sqft', 'bath',
                                                   'bhk'])])),
                ('model', LinearRegression())])

In [49]:
y_pred_lr = pipe_lr.predict(X_test)

In [50]:
r2_score_lr = r2_score(y_test,y_pred_lr)
print(r2_score_lr)

0.823377245749841

### apply Lasso

In [56]:
# Complete pipeline
pipe_lasso = Pipeline([
    ('preprocessor', preprocessor),
    ('lasso', Lasso())
])

In [58]:
pipe_lasso.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location']),
                                                 ('num', StandardScaler(),
                                                  ['total_sqft', 'bath',
                                                   'bhk'])])),
                ('lasso', Lasso())])

In [59]:
y_pred_lasso = pipe_lasso.predict(X_test)

In [60]:
r2_score_lasso = r2_score(y_test,y_pred_lasso)
print(r2_score_lasso)

0.670430126831282

### apply ridge regression

In [61]:
pipe_ridge = Pipeline([
    ("preprocessor" , preprocessor),
    ("ridge", Ridge())
])

In [62]:
pipe_ridge.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location']),
                                                 ('num', StandardScaler(),
                                                  ['total_sqft', 'bath',
                                                   'bhk'])])),
                ('ridge', Ridge())])

In [64]:
y_pred_ridge = pipe_ridge.predict(X_test)

In [65]:
print(r2_score(y_test,y_pred_ridge))

0.8203010408114004

In [66]:
import pickle

pickle.dump(pipe_ridge,open("RidgeModel.pkl","wb"))

In [67]:
import os

print(os.getcwd())
print(os.listdir())

/content
['.config', 'drive', 'RidgeModel.pkl', 'sample_data']

In [68]:
from google.colab import files

files.download("RidgeModel.pkl")

# Call PKL Object

In [69]:
import pickle

In [70]:
pipe = pickle.load(open("RidgeModel.pkl","rb"))

In [74]:
location = "1st Phase JP Nagar"
total_sqft = 1000
bath = 2.0
bhk = 2.0

input_df = pd.DataFrame([[location, total_sqft, bath, bhk]], columns=['location','total_sqft','bath','bhk'])

In [75]:
result = pipe.predict(input_df)

In [77]:
print(type(result))

<class 'numpy.ndarray'>

In [79]:
print(result[0] * 100000)

8596330.272038449